In [35]:
import numpy as np
from queue import PriorityQueue

In [83]:
initial_state = (np.array([2,5,7,1,-1,8,9,3,4]),np.array([5,1,8,3]))


In [24]:
def print_state(state):
    for j in range(3):
        for i in range(3):
            print(f"{state[i+3*j]}",end=" ")
        print("\n")

In [60]:
print_state(initial_state[0])

2 5 7 

1 -1 8 

9 3 4 



In [34]:
def goal_check(state):
    return np.all(state == np.array([1,2,3,4,5,6,7,8,-1]))

In [84]:
queue = PriorityQueue()
queue.put(initial_state)

current_state,state_to_move = queue.get()

In [165]:
#while not goal_check(current_state):
idx_hole = int(np.where(current_state==-1)[0].item())
for i in state_to_move:
    idx_to_change = int(np.where(current_state==i)[0].item())
    tmp = current_state.copy()
    tmp[idx_hole] = i
    tmp[idx_to_change] = -1
    tmp_move = []
    if idx_to_change-3>=0:
        tmp_move.append(tmp[idx_to_change-3])
        
    if idx_to_change+3<3*3:
        tmp_move.append(tmp[idx_to_change+3])
    
    if idx_to_change>3*np.floor((idx_to_change+1)/3):
        tmp_move.append(tmp[idx_to_change-1])

    if idx_to_change<3+3*np.floor((idx_to_change+1)/3):
        tmp_move.append(tmp[idx_to_change+1])

    new_state = (np.array(tmp),np.array(tmp_move))
    
    print(new_state)
    print(idx_to_change)
    print(f"Res{3*np.floor((idx_to_change)/3)}")
    print(f"Res--{3+3*np.floor((idx_to_change)/3)}")
        

(array([ 2, -1,  7,  1,  5,  8,  9,  3,  4]), array([5, 2, 7]))
1
Res0.0
Res--3.0
(array([ 2,  5,  7, -1,  1,  8,  9,  3,  4]), array([2, 9, 1]))
3
Res3.0
Res--6.0
(array([ 2,  5,  7,  1,  8, -1,  9,  3,  4]), array([7, 4, 8, 9]))
5
Res3.0
Res--6.0
(array([ 2,  5,  7,  1,  3,  8,  9, -1,  4]), array([3, 9, 4]))
7
Res6.0
Res--9.0
