Implement the set-covering game

In [2]:
import numpy as np
from random import random
from functools import reduce
from queue import PriorityQueue

In [3]:
PROBLEM_SIZE = 5
NUM_SETS = 10

In [103]:
sets = [np.array([random() < .2 for _ in range(PROBLEM_SIZE)]) for _ in range(NUM_SETS)]
assert np.all(reduce(np.logical_or,[sets[i] for i in range(NUM_SETS)])), "Not solvable"
sets



#random() return a number, if it's <0.2 then i'll have true, otherwise false
#the goal is to find the minimun number of sets which OR returns all true.
#EXAMPLE:
# array([False, False,  True,  True,  True])
# array([ True,  True, False, False, False])
# The OR will be all true, so this is a solution!!

[array([ True,  True,  True,  True, False]),
 array([False, False, False,  True, False]),
 array([False,  True,  True, False,  True]),
 array([False, False, False, False, False]),
 array([False, False, False, False, False]),
 array([False, False, False, False, False]),
 array([False,  True, False, False, False]),
 array([False,  True, False, False,  True]),
 array([False, False, False, False,  True]),
 array([False, False, False, False, False])]

In [157]:
state = ({1,3,5}, {0,2,4,6,7})
#We took 1,3,5 and not taken 0,2,4,6,7, we'll rapresent the states in this way, 2 sets.

In [67]:
def goal_check(state):
    return np.all(reduce(np.logical_or,[sets[i] for i in state[1][0]],np.array([False for _ in range(PROBLEM_SIZE)])))
#the reduce does the OR operation on the sets[i] for i in state[0], so the elements taken!!. Then return the AND between the elementes returned
# by the reduce (by the np.all()).

In [55]:
goal_check((0,(set({7,6}),set())))

True

In [104]:
#We use a PriorityQueue whose cost is the n umber of taken elements, so the number of elements that are in the first set of the state
frontier = PriorityQueue()
initial_state = (set(),set(range(NUM_SETS))) #everithing not taken !
frontier.put((0,initial_state)) #the number of taken elements is 0, everything is not taken

state = frontier.get()

while not goal_check(state):
    for a in state[1][1]: #in state[1][1] I have all the elements that I didn't take
        new_state = (state[1][0] | {a}, state[1][1] - {a}) #The | is UNION, - is DIFFERENCE
        frontier.put((len(new_state[0]),new_state))
    state = frontier.get()

In [105]:
print(goal_check(state))
state

True


(2, ({0, 2}, {1, 3, 4, 5, 6, 7, 8, 9}))