Implement the set-covering game

In [106]:
import numpy as np
from random import random
from functools import reduce
from queue import PriorityQueue

In [107]:
PROBLEM_SIZE = 5
NUM_SETS = 10

In [113]:
sets = [np.array([random() < .2 for _ in range(PROBLEM_SIZE)]) for _ in range(NUM_SETS)]
assert np.all(reduce(np.logical_or,[sets[i] for i in range(NUM_SETS)])), "Not solvable"
sets



#random() return a number, if it's <0.2 then i'll have true, otherwise false
#the goal is to find the minimun number of sets which OR returns all true.
#EXAMPLE:
# array([False, False,  True,  True,  True])
# array([ True,  True, False, False, False])
# The OR will be all true, so this is a solution!!

[array([False, False, False, False, False]),
 array([False, False, False,  True, False]),
 array([ True, False, False, False,  True]),
 array([False, False, False, False,  True]),
 array([False, False, False, False, False]),
 array([False, False,  True,  True,  True]),
 array([False, False, False, False, False]),
 array([False, False,  True, False, False]),
 array([False, False, False,  True, False]),
 array([False,  True, False, False, False])]

In [109]:
state = ({1,3,5}, {0,2,4,6,7})
#We took 1,3,5 and not taken 0,2,4,6,7, we'll rapresent the states in this way, 2 sets.

In [110]:
def goal_check(state):
    return np.all(reduce(np.logical_or,[sets[i] for i in state[0]],np.array([False for _ in range(PROBLEM_SIZE)])))
#the reduce does the OR operation on the sets[i] for i in state[0], so the elements taken!!. Then return the AND between the elementes returned
# by the reduce (by the np.all()).

def distance(state):
    return PROBLEM_SIZE - sum(reduce(np.logical_or,[sets[i] for i in state[0]],np.array([False for _ in range(PROBLEM_SIZE)])))
#This function  return the distance of the state from the goal. That's the number of false we still have and
# that has to be covered. The sum returs us the number of true value. 

def actual_cost(state):
    return len(state[0]) #The actual cost is the number of elements I have in the first set

def f(n):
    return actual_cost(n) + distance(n) #This is the A* function

In [119]:
#We use a PriorityQueue whose cost is the n umber of taken elements, so the number of elements that are in the first set of the state
frontier = PriorityQueue()
initial_state = (set(),set(range(NUM_SETS))) #everithing not taken !
frontier.put((f(initial_state),initial_state))

_,state = frontier.get()

while not goal_check(state):
    for a in state[1]: #in state[1] I have all the elements that I didn't take
        new_state = (state[0] | {a}, state[1] - {a}) #The | is UNION, - is DIFFERENCE
        frontier.put((f(new_state),new_state))
    _,state = frontier.get()

In [122]:
print(f(state))
print(frontier.get())
state

3
(4, ({8, 2, 5}, {0, 1, 3, 4, 6, 7, 9}))


({2, 5, 9}, {0, 1, 3, 4, 6, 7, 8})