Implement the set-covering game

In [417]:
import numpy as np
from random import random
from functools import reduce
from queue import PriorityQueue

In [418]:
PROBLEM_SIZE = 20
NUM_SETS = 10

In [419]:
sets = [np.array([random() < .3 for _ in range(PROBLEM_SIZE)]) for _ in range(NUM_SETS)]
assert np.all(reduce(np.logical_or,[sets[i] for i in range(NUM_SETS)])), "Not solvable"
sets



#random() return a number, if it's <0.2 then i'll have true, otherwise false
#the goal is to find the minimun number of sets which OR returns all true.
#EXAMPLE:
# array([False, False,  True,  True,  True])
# array([ True,  True, False, False, False])
# The OR will be all true, so this is a solution!!

[array([False,  True, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False,  True,
         True, False]),
 array([False,  True, False, False,  True, False, False, False,  True,
        False,  True, False,  True,  True, False,  True, False, False,
         True, False]),
 array([False, False,  True,  True,  True,  True,  True, False, False,
        False, False,  True, False, False, False, False,  True,  True,
         True,  True]),
 array([ True, False, False, False, False, False,  True, False, False,
        False, False, False,  True,  True,  True, False,  True,  True,
         True, False]),
 array([ True, False, False,  True, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True, False,
        False,  True]),
 array([False,  True,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False]),
 arr

In [420]:
state = ({1,3,5}, {0,2,4,6,7})
#We took 1,3,5 and not taken 0,2,4,6,7, we'll rapresent the states in this way, 2 sets.

In [421]:
def goal_check(state):
    return np.all(reduce(np.logical_or,[sets[i] for i in state[0]],np.array([False for _ in range(PROBLEM_SIZE)])))
#the reduce does the OR operation on the sets[i] for i in state[0], so the elements taken!!. Then return the AND between the elementes returned
# by the reduce (by the np.all()).

def distance(state):
    return PROBLEM_SIZE - sum(reduce(np.logical_or,[sets[i] for i in state[0]],np.array([False for _ in range(PROBLEM_SIZE)])))
#This function  return the distance of the state from the goal. That's the number of false we still have and
# that has to be covered. The sum returs us the number of true value. 

def h(state):
    return np.ceil((sum(sum(sets[s] for s in state[1]))) / (PROBLEM_SIZE-len(state[0])))
    

def actual_cost(state):
    return len(state[0]) #The actual cost is the number of elements I have in the first set

def f(n):
    return actual_cost(n) + h(n) #This is the A* function

In [422]:
state = ({0},{1,2,4,3,5,6,7})
print((sum(sum(sets[s] for s in state[1]))) / (PROBLEM_SIZE-len(state[0])))
h(state) , distance(state), len(state[0])

2.4210526315789473


(3.0, 16, 1)

In [423]:
#We use a PriorityQueue whose cost is the n umber of taken elements, so the number of elements that are in the first set of the state
frontier = PriorityQueue()
initial_state = (set(),set(range(NUM_SETS))) #everithing not taken !
frontier.put((f(initial_state),initial_state))

_,state = frontier.get()
counter =0 
while not goal_check(state):
    for a in state[1]: #in state[1] I have all the elements that I didn't take
        counter+=1
        new_state = (state[0] | {a}, state[1] - {a}) #The | is UNION, - is DIFFERENCE
        frontier.put((f(new_state),new_state))
    _,state = frontier.get()

In [424]:
print(counter)
state

762


({2, 3, 8, 9}, {0, 1, 4, 5, 6, 7})

In [425]:
#We use a PriorityQueue whose cost is the n umber of taken elements, so the number of elements that are in the first set of the state
frontier = PriorityQueue()
initial_state = (set(),set(range(NUM_SETS))) #everithing not taken !
frontier.put(initial_state) #the number of taken elements is 0, everything is not taken

state = frontier.get()

while not goal_check(state):
    for a in state[1]: #in state[1][1] I have all the elements that I didn't take
        new_state = (state[0] | {a}, state[1] - {a}) #The | is UNION, - is DIFFERENCE
        frontier.put(new_state)
    state = frontier.get()

In [426]:
print(state)

({8, 9, 2, 7}, {0, 1, 3, 4, 5, 6})
